// packages/vue3/src/components/EditRoomModal.vue
<template>
  <t-dialog
    v-model:visible="dialogVisible"
    header="编辑直播间"
    :width="560"
    placement="center"
    class="edit-room-modal"
    @close="handleClose"
  >
    <t-form class="edit-room-form" :label-width="100" :colon="false">
      <!-- 直播间ID -->
      <t-form-item label="直播间 ID">
        <t-input
          :value="roomId"
          disabled
          readonly
        />
      </t-form-item>

      <!-- 直播间标题 -->
      <t-form-item label="直播间标题" :required-mark="true">
        <t-input
          v-model="formData.title"
          placeholder="请输入直播间标题"
          :status="titleBytes > 100 ? 'error' : 'default'"
          :tips="titleBytes > 100 ? '标题不能超过 100 字节' : ''"
        >
          <template #suffix>
            <span class="input-suffix-count" :class="{ 'byte-overflow': titleBytes > 100 }">
              {{ titleBytes }}/100
            </span>
          </template>
        </t-input>
      </t-form-item>

      <!-- 直播间封面 -->
      <t-form-item label="直播间封面">
        <ImageUpload
          ref="coverUploadRef"
          v-model="formData.coverUrl"
          type="cover"
          :upload-enabled="uploadEnabled"
          :crop-enabled="true"
          :aspect-ratio="coverAspectRatio"
          placeholder="点击或拖拽上传封面图片"
          :preview-height="140"
          :max-bytes="200"
          :defer-upload="uploadEnabled"
          @file-ready="handleFileReady"
        />
      </t-form-item>

      <!-- 自定义信息 - 折叠/展开区域 -->
      <div class="custom-info-section">
        <div class="custom-info-toggle" @click="customInfoExpanded = !customInfoExpanded">
          <ChevronDownIcon v-if="customInfoExpanded" :size="16" />
          <ChevronRightIcon v-else :size="16" />
          <span>自定义信息</span>
          <span v-if="customInfos.length > 0" class="custom-info-count">{{ customInfos.length }}</span>
        </div>
        <div v-if="customInfoExpanded" class="custom-info-container">
          <div v-for="(info, index) in customInfos" :key="index" class="custom-info-row">
            <div class="custom-input-wrap">
              <t-input
                v-model="info.key"
                placeholder="请输入Key"
                :status="getKeyBytes(info.key) > CUSTOM_INFO_LIMITS.maxKeyBytes || isCustomInfoKeyMissing(info) ? 'error' : 'default'"
                :tips="getKeyBytes(info.key) > CUSTOM_INFO_LIMITS.maxKeyBytes ? `Key 超出 ${CUSTOM_INFO_LIMITS.maxKeyBytes} 字节限制` : isCustomInfoKeyMissing(info) ? '填写了 Value 时必须填写 Key' : ''"
              />
            </div>
            <div class="custom-input-wrap custom-value-wrap">
              <t-input
                v-model="info.value"
                placeholder="请输入Value"
                :status="getValueBytes(info.value) > CUSTOM_INFO_LIMITS.maxValueBytes ? 'error' : 'default'"
                :tips="getValueBytes(info.value) > CUSTOM_INFO_LIMITS.maxValueBytes ? 'Value 超出 2KB 限制' : ''"
              />
            </div>
            <t-button variant="text" shape="circle" @click="removeCustomInfo(index)">
              <CloseIcon />
            </t-button>
          </div>
          <t-button style="width:80px"
            v-if="customInfos.length < CUSTOM_INFO_LIMITS.maxCount"
            variant="text"
            shape="round"
            @click="addCustomInfo"
            theme="primary"
          >
            <template #icon><AddIcon /></template>
            添加
          </t-button>
        </div>
      </div>
    </t-form>

    <template #footer>
      <div class="dialog-footer">
        <t-button variant="outline" shape="round" @click="handleClose">取消</t-button>
        <t-button theme="primary" shape="round" :loading="saving" :disabled="saving || !formData.title.trim() || coverUploadRef?.isValidating || coverUploadRef?.hasUrlError" @click="handleSubmit">
          {{ saving ? '保存中...' : '保存' }}
        </t-button>
      </div>
    </template>
  </t-dialog>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { ChevronDownIcon, ChevronRightIcon, AddIcon, CloseIcon } from 'tdesign-icons-vue-next';
import { MessagePlugin } from 'tdesign-vue-next';
import { updateRoomInfo, getRoomDetail } from '@/api/room';
import { resolveImageUploadUrl, ImageUploadResolveError } from '@live-manager/common';
import ImageUpload from './ImageUpload.vue';
import type { RoomInfo, RoomListItem } from '@/types';

interface Props {
  visible: boolean;
  room: (RoomInfo & { RoomId?: string; RoomName?: string; CoverURL?: string }) | RoomListItem | null;
  uploadEnabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  uploadEnabled: false,
});

// 获取房间ID（兼容两种类型）
const roomId = computed(() => {
  if (!props.room) return '';
  // RoomListItem 类型有 RoomId 字段
  if ('RoomId' in props.room && props.room.RoomId) {
    return props.room.RoomId;
  }
  // RoomInfo 类型有 id 字段
  if ('id' in props.room && props.room.id) {
    return props.room.id;
  }
  return '';
});

const emit = defineEmits<{
  'update:visible': [value: boolean];
  'success': [updatedFields: { roomName: string; coverUrl: string }];
}>();

const dialogVisible = computed({
  get: () => props.visible,
  set: (val) => emit('update:visible', val),
});

interface CustomInfo {
  key: string;
  value: string;
}

interface EditRoomFormData {
  title: string;
  coverUrl: string;
}

const CUSTOM_INFO_LIMITS = {
  maxCount: 10,
  maxKeyBytes: 50,
  maxValueBytes: 2 * 1024,
  maxTotalValueBytes: 16 * 1024,
};

function getByteLength(str: string): number {
  return new TextEncoder().encode(str).length;
}

const getKeyBytes = (key: string) => getByteLength(key);
const getValueBytes = (value: string) => getByteLength(value);

function detectImageAspectRatio(url: string): Promise<number> {
  return new Promise((resolve) => {
    if (!url) {
      resolve(9 / 16);
      return;
    }
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const ratio = img.naturalWidth / img.naturalHeight;
      resolve(ratio > 1 ? 16 / 9 : 9 / 16);
    };
    img.onerror = () => resolve(9 / 16);
    img.src = url;
  });
}

const formData = ref<EditRoomFormData>({
  title: '',
  coverUrl: '',
});

const customInfos = ref<CustomInfo[]>([]);
const customInfoExpanded = ref(false);
const initialKeys = ref<string[]>([]);
const coverAspectRatio = ref(9 / 16);
const saving = ref(false);

// 封面延迟上传相关
const coverUploadRef = ref<InstanceType<typeof ImageUpload> | null>(null);
const hasPendingCover = ref(false);

const handleFileReady = (file: File | Blob | null) => {
  hasPendingCover.value = !!file;
};

const titleBytes = computed(() => getByteLength(formData.value.title));
const validCustomInfoCount = computed(() => customInfos.value.filter(i => i.key.trim()).length);

const isCustomInfoKeyMissing = (info: CustomInfo) => !info.key.trim() && !!info.value.trim();

// 监听 room 变化，加载表单数据
watch([() => props.room, () => props.visible], async ([room, visible]) => {
  if (room && visible) {
    // 兼容两种类型：RoomListItem (RoomName, CoverURL) 和 RoomInfo (title, coverUrl)
    const title = 'RoomName' in room ? room.RoomName : (room.title || '');
    const coverUrl = 'CoverURL' in room ? room.CoverURL : (room.coverUrl || '');
    const id = 'RoomId' in room ? room.RoomId : room.id;

    formData.value = {
      title: title || '',
      coverUrl: coverUrl || '',
    };

    // 检测封面宽高比
    if (coverUrl) {
      coverAspectRatio.value = await detectImageAspectRatio(coverUrl);
    } else {
      coverAspectRatio.value = 9 / 16;
    }

    // 加载自定义信息
    try {
      const res = await getRoomDetail(id);
      const roomInfo = res?.Response?.RoomInfo;
      if (roomInfo?.CustomInfo && typeof roomInfo.CustomInfo === 'object') {
        const infos = Object.entries(roomInfo.CustomInfo).map(([key, value]) => ({
          key,
          value: String(value),
        }));
        customInfos.value = infos;
        customInfoExpanded.value = infos.length > 0;
        initialKeys.value = infos.map(i => i.key);
      } else {
        customInfos.value = [];
        customInfoExpanded.value = false;
        initialKeys.value = [];
      }
    } catch {
      // 从 room 中获取自定义信息
      const customInfo = 'CustomInfo' in room ? room.CustomInfo : room.customInfo;
      if (customInfo && typeof customInfo === 'object') {
        // CustomInfo 在 RoomListItem 中是 string 类型，需要解析
        if (typeof customInfo === 'string') {
          try {
            const parsed = JSON.parse(customInfo);
            const infos = Object.entries(parsed).map(([key, value]) => ({
              key,
              value: String(value),
            }));
            customInfos.value = infos;
            customInfoExpanded.value = infos.length > 0;
            initialKeys.value = infos.map(i => i.key);
          } catch {
            customInfos.value = [];
            customInfoExpanded.value = false;
            initialKeys.value = [];
          }
        } else {
          const infos = Object.entries(customInfo).map(([key, value]) => ({
            key,
            value: String(value),
          }));
          customInfos.value = infos;
          customInfoExpanded.value = infos.length > 0;
          initialKeys.value = infos.map(i => i.key);
        }
      } else {
        customInfos.value = [];
        customInfoExpanded.value = false;
        initialKeys.value = [];
      }
    }
  }
}, { immediate: true });

const addCustomInfo = () => {
  if (customInfos.value.length >= CUSTOM_INFO_LIMITS.maxCount) {
    MessagePlugin.error(`自定义信息最多 ${CUSTOM_INFO_LIMITS.maxCount} 条`);
    return;
  }
  customInfos.value.push({ key: '', value: '' });
};

const removeCustomInfo = (index: number) => {
  customInfos.value.splice(index, 1);
};

const handleClose = () => {
  customInfos.value = [];
  customInfoExpanded.value = false;
  initialKeys.value = [];
  hasPendingCover.value = false;
  // 清理 ImageUpload 组件内部状态（取消验证、清理缓存预览）
  coverUploadRef.value?.reset();
  // 清空表单数据，确保下次打开时 modelValue 从空变为有值，触发 ImageUpload 的 watch 重新同步
  formData.value = { title: '', coverUrl: '' };
  emit('update:visible', false);
};

const handleSubmit = async () => {
  if (!props.room) return;

  if (!formData.value.title.trim()) {
    MessagePlugin.error('请输入直播间标题');
    return;
  }

  if (titleBytes.value > 100) {
    MessagePlugin.error(`标题不能超过 100 字节（当前 ${titleBytes.value} 字节）`);
    return;
  }

  if (customInfos.value.some(isCustomInfoKeyMissing)) {
    MessagePlugin.error('自定义信息填写了 Value 时必须填写 Key');
    return;
  }

  saving.value = true;

  try {
    // 解析封面 URL（公共逻辑自动处理 URL 验证 / 文件上传 / fallback）
    let coverUrl = '';
    try {
      coverUrl = await resolveImageUploadUrl({
        handle: coverUploadRef.value as any,
        hasPendingFile: hasPendingCover.value,
        fallbackUrl: formData.value.coverUrl,
        label: '封面图片',
      });
    } catch (err: any) {
      MessagePlugin.error(err instanceof ImageUploadResolveError ? err.message : `封面处理失败: ${err.message || '未知错误'}`);
      saving.value = false;
      return;
    }

    // 构建自定义信息
    const customInfo: Record<string, string> = {};
    let totalValueBytes = 0;

    for (const info of customInfos.value) {
      const trimmedKey = info.key.trim();
      if (!trimmedKey) continue;

      const keyBytes = getByteLength(trimmedKey);
      if (keyBytes > CUSTOM_INFO_LIMITS.maxKeyBytes) {
        MessagePlugin.error(`Key "${trimmedKey}" 超过 ${CUSTOM_INFO_LIMITS.maxKeyBytes} 字节限制`);
        saving.value = false;
        return;
      }

      const valueBytes = getByteLength(info.value);
      if (valueBytes > CUSTOM_INFO_LIMITS.maxValueBytes) {
        MessagePlugin.error(`Key "${trimmedKey}" 的 Value 超过 2KB 限制`);
        saving.value = false;
        return;
      }

      totalValueBytes += valueBytes;
      customInfo[trimmedKey] = info.value;
    }

    if (Object.keys(customInfo).length > CUSTOM_INFO_LIMITS.maxCount) {
      MessagePlugin.error(`自定义信息最多 ${CUSTOM_INFO_LIMITS.maxCount} 条`);
      saving.value = false;
      return;
    }

    if (totalValueBytes > CUSTOM_INFO_LIMITS.maxTotalValueBytes) {
      MessagePlugin.error(`所有 Value 总大小超过 16KB 限制`);
      saving.value = false;
      return;
    }

    // 计算被删除的 keys
    const currentKeys = new Set(Object.keys(customInfo));
    const deleteKeys = initialKeys.value.filter(k => !currentKeys.has(k));

    const response = await updateRoomInfo(roomId.value, {
      roomName: formData.value.title.trim(),
      coverUrl: coverUrl || undefined,
      customInfo: Object.keys(customInfo).length > 0 ? customInfo : undefined,
      deleteKeys: deleteKeys.length > 0 ? deleteKeys : undefined,
    });

    if (response.ErrorCode === 0 || response.ErrorCode === undefined) {
      MessagePlugin.success('直播间信息已更新');
      emit('success', {
        roomName: formData.value.title.trim(),
        coverUrl: coverUrl,
      });
      handleClose();
    } else {
      MessagePlugin.error(`更新失败: ${response.ErrorMessage || '未知错误'}`);
    }
  } catch (error: any) {
    MessagePlugin.error(`请求失败: ${error.message || '网络错误'}`);
  } finally {
    saving.value = false;
  }
};
</script>

<style scoped>
/* TDesign Form 适配 */
.edit-room-modal :deep(.t-form__item) {
  margin-bottom: 16px;
}

.edit-room-modal :deep(.t-form__item:last-child) {
  margin-bottom: 0;
}

/* 输入框内的字节计数后缀 */
.input-suffix-count {
  color: rgba(0, 0, 0, 0.4);
  font-size: 14px;
  white-space: nowrap;
}

.input-suffix-count.byte-overflow {
  color: #E34D59;
}

/* ImageUpload 在 FormItem 内自适应宽度 */
.edit-room-modal :deep(.t-form__controls-content .image-upload-container) {
  width: 100%;
}

.field-hint {
  margin-left: 8px;
  font-size: 12px;
  color: #888;
  font-weight: normal;
}

/* 自定义信息折叠/展开区域 */
.custom-info-section {
  margin-top: 4px;
}

.custom-info-toggle {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  cursor: pointer;
  user-select: none;
  font-size: 14px;
  color: rgba(0, 0, 0, 0.6);
  padding: 4px 0;
  transition: color 0.2s;
}

.custom-info-toggle:hover {
  color: rgba(0, 0, 0, 0.9);
}

.custom-info-count {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 18px;
  height: 18px;
  padding: 0 5px;
  border-radius: 9px;
  background: #E3F1FC;
  color: #1C66E5;
  font-size: 12px;
  line-height: 1;
  margin-left: 4px;
}

/* 自定义信息 */
.custom-info-container {
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 100%;
  margin-top: 8px;
}

.custom-info-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.custom-input-wrap {
  flex: 1;
}

.custom-value-wrap {
  flex: 2;
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
</style>

// packages/react/src/components/EditRoomModal.tsx
import { useState, useEffect, useRef } from 'react';
import { ChevronDownIcon, ChevronRightIcon, AddIcon, CloseIcon } from 'tdesign-icons-react';
import { Button, Dialog, Input } from 'tdesign-react';
import { Message } from './Toast';
import { updateRoomInfo, getRoomDetail } from '../api/room';
import ImageUpload from './ImageUpload';
import type { ImageUploadRef } from './ImageUpload';
import type { RoomInfo } from '../types';
import { FormLayout, FormField } from './FormField';
import { DIALOG_WIDTH, resolveImageUploadUrl, ImageUploadResolveError } from '@live-manager/common';
import './EditRoomModal.css';

/** 加载图片并返回其宽高比，失败时返回默认值 9:16（竖屏） */
function detectImageAspectRatio(url: string): Promise<number> {
  return new Promise((resolve) => {
    if (!url) {
      resolve(9 / 16);
      return;
    }
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const ratio = img.naturalWidth / img.naturalHeight;
      // 宽高比 > 1 为横屏，使用 16:9；否则为竖屏，使用 9:16
      resolve(ratio > 1 ? 16 / 9 : 9 / 16);
    };
    img.onerror = () => resolve(9 / 16);
    img.src = url;
  });
}

interface EditRoomModalProps {
  visible: boolean;
  room: RoomInfo | null;
  onClose: () => void;
  onSuccess: (updatedFields: { roomName: string; coverUrl: string }) => void;
  uploadEnabled?: boolean;
}

interface CustomInfo {
  key: string;
  value: string;
}

interface EditRoomFormData {
  title: string;
  coverUrl: string;
}

// 自定义信息限制
const CUSTOM_INFO_LIMITS = {
  maxCount: 10,
  maxKeyBytes: 50,
  maxValueBytes: 2 * 1024,       // 2KB
  maxTotalValueBytes: 16 * 1024,  // 16KB
};

/** 计算字符串的 UTF-8 字节长度 */
function getByteLength(str: string): number {
  return new TextEncoder().encode(str).length;
}

export default function EditRoomModal({ visible, room, onClose, onSuccess, uploadEnabled = false }: EditRoomModalProps) {
  const [formData, setFormData] = useState<EditRoomFormData>({
    title: '',
    coverUrl: '',
  });
  const [customInfos, setCustomInfos] = useState<CustomInfo[]>([]);
  const [customInfoExpanded, setCustomInfoExpanded] = useState(false);
  // 记录初始加载时的 keys，用于提交时计算被删除的 keys
  const initialKeysRef = useRef<string[]>([]);
  // 根据已有封面图片检测到的裁剪宽高比
  const [coverAspectRatio, setCoverAspectRatio] = useState<number>(9 / 16);

  const [saving, setSaving] = useState(false);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [successMsg, setSuccessMsg] = useState('');

  // 封面延迟上传相关
  const coverUploadRef = useRef<ImageUploadRef>(null);
  const [hasPendingCover, setHasPendingCover] = useState(false);

  // 当封面 URL 变化时，检测图片实际宽高比
  useEffect(() => {
    if (room?.coverUrl) {
      detectImageAspectRatio(room.coverUrl).then(setCoverAspectRatio);
    } else {
      setCoverAspectRatio(9 / 16);
    }
  }, [room?.coverUrl]);

  useEffect(() => {
    if (room && visible) {
      setFormData({
        title: room.title || '',
        coverUrl: room.coverUrl || '',
      });
      // 主动获取房间详情以加载自定义信息
      setLoadingDetail(true);
      getRoomDetail(room.id)
        .then((res) => {
          const roomInfo = res?.Response?.RoomInfo;
          if (roomInfo?.CustomInfo && typeof roomInfo.CustomInfo === 'object') {
            const infos = Object.entries(roomInfo.CustomInfo).map(([key, value]) => ({
              key,
              value: String(value),
            }));
            setCustomInfos(infos);
            setCustomInfoExpanded(infos.length > 0);
            initialKeysRef.current = infos.map(i => i.key);
          } else {
            setCustomInfos([]);
            setCustomInfoExpanded(false);
            initialKeysRef.current = [];
          }
        })
        .catch(() => {
          if (room.customInfo && typeof room.customInfo === 'object') {
            const infos = Object.entries(room.customInfo).map(([key, value]) => ({
              key,
              value: String(value),
            }));
            setCustomInfos(infos);
            setCustomInfoExpanded(infos.length > 0);
            initialKeysRef.current = infos.map(i => i.key);
          } else {
            setCustomInfos([]);
            setCustomInfoExpanded(false);
            initialKeysRef.current = [];
          }
        })
        .finally(() => setLoadingDetail(false));
    }
  }, [room, visible]);

  // 添加自定义信息
  const addCustomInfo = () => {
    if (customInfos.length >= CUSTOM_INFO_LIMITS.maxCount) {
      showMessage('error', `自定义信息最多 ${CUSTOM_INFO_LIMITS.maxCount} 条`);
      return;
    }
    setCustomInfos([...customInfos, { key: '', value: '' }]);
  };

  // 更新自定义信息
  const updateCustomInfo = (index: number, field: 'key' | 'value', value: string) => {
    const newInfos = [...customInfos];
    newInfos[index][field] = value;
    setCustomInfos(newInfos);
  };

  // 删除自定义信息
  const removeCustomInfo = (index: number) => {
    setCustomInfos(customInfos.filter((_, i) => i !== index));
  };

  const isCustomInfoKeyMissing = (info: CustomInfo) => !info.key.trim() && !!info.value.trim();

  const showMessage = (type: 'success' | 'error', msg: string) => {
    if (type === 'success') {
      Message.success(msg);
    } else {
      Message.error(msg);
    }
  };

  // 关闭弹窗
  const handleClose = () => {
    setErrorMsg('');
    setSuccessMsg('');
    setCustomInfos([]);
    setCustomInfoExpanded(false);
    initialKeysRef.current = [];
    setHasPendingCover(false);
    // 清理 ImageUpload 组件内部状态（取消验证、清理缓存预览）
    coverUploadRef.current?.reset();
    // 清空表单数据，确保下次打开时 value 从空变为有值，触发 ImageUpload 的 useEffect 重新同步
    setFormData({ title: '', coverUrl: '' });
    onClose();
  };

  // 提交表单
  const handleSubmit = async () => {
    if (!room) return;

    // 验证
    if (!formData.title.trim()) {
      showMessage('error', '请输入直播间标题');
      return;
    }
    const titleBytes = getByteLength(formData.title);
    if (titleBytes > 100) {
      showMessage('error', `标题不能超过 100 字节（当前 ${titleBytes} 字节）`);
      return;
    }

    if (customInfos.some(isCustomInfoKeyMissing)) {
      showMessage('error', '自定义信息填写了 Value 时必须填写 Key');
      return;
    }

    setSaving(true);
    setErrorMsg('');

    try {
      // 解析封面 URL（公共逻辑自动处理 URL 验证 / 文件上传 / fallback）
      let coverUrl = '';
      try {
        coverUrl = await resolveImageUploadUrl({
          handle: coverUploadRef.current,
          hasPendingFile: hasPendingCover,
          fallbackUrl: formData.coverUrl,
          label: '封面图片',
        });
      } catch (err: any) {
        showMessage('error', err instanceof ImageUploadResolveError ? err.message : `封面处理失败: ${err.message || '未知错误'}`);
        setSaving(false);
        return;
      }

      // 构建自定义信息对象
      const customInfo: Record<string, string> = {};
      let totalValueBytes = 0;
      for (const info of customInfos) {
        const trimmedKey = info.key.trim();
        if (!trimmedKey) continue;

        const keyBytes = getByteLength(trimmedKey);
        if (keyBytes > CUSTOM_INFO_LIMITS.maxKeyBytes) {
          showMessage('error', `Key "${trimmedKey}" 超过 ${CUSTOM_INFO_LIMITS.maxKeyBytes} 字节限制（当前 ${keyBytes} 字节）`);
          setSaving(false);
          return;
        }

        const valueBytes = getByteLength(info.value);
        if (valueBytes > CUSTOM_INFO_LIMITS.maxValueBytes) {
          showMessage('error', `Key "${trimmedKey}" 的 Value 超过 2KB 限制（当前 ${valueBytes} 字节）`);
          setSaving(false);
          return;
        }

        totalValueBytes += valueBytes;
        customInfo[trimmedKey] = info.value;
      }

      if (Object.keys(customInfo).length > CUSTOM_INFO_LIMITS.maxCount) {
        showMessage('error', `自定义信息最多 ${CUSTOM_INFO_LIMITS.maxCount} 条`);
        setSaving(false);
        return;
      }

      if (totalValueBytes > CUSTOM_INFO_LIMITS.maxTotalValueBytes) {
        showMessage('error', `所有 Value 总大小超过 16KB 限制（当前 ${(totalValueBytes / 1024).toFixed(1)}KB）`);
        setSaving(false);
        return;
      }

      // 计算被删除的 keys（初始有但当前没有的）
      const currentKeys = new Set(Object.keys(customInfo));
      const deleteKeys = initialKeysRef.current.filter(k => !currentKeys.has(k));

      console.log('[EditRoomModal] initialKeys:', initialKeysRef.current, 'currentKeys:', [...currentKeys], 'deleteKeys:', deleteKeys);

      const response = await updateRoomInfo(room.id, {
        roomName: formData.title.trim(),
        coverUrl: coverUrl || undefined,
        customInfo: Object.keys(customInfo).length > 0 ? customInfo : undefined,
        deleteKeys: deleteKeys.length > 0 ? deleteKeys : undefined,
      });

      if (response.ErrorCode === 0 || response.ErrorCode === undefined) {
        showMessage('success', '直播间信息已更新');

        setTimeout(() => {
          onSuccess({
            roomName: formData.title.trim(),
            coverUrl: coverUrl,
          });
          handleClose();
        }, 500);
      } else {
        showMessage('error', `更新失败: ${response.ErrorMessage || '未知错误'}`);
      }
    } catch (error: any) {
      showMessage('error', `请求失败: ${error.message || '网络错误'}`);
    } finally {
      setSaving(false);
    }
  };

  if (!visible || !room) return null;

  return (
    <Dialog
      key={`edit-room-${room?.id}`}
      destroyOnClose
      visible={visible}
      header="编辑直播间"
      onClose={handleClose}
      width={DIALOG_WIDTH.FORM}
      placement="center"
      className="edit-room-modal"
      footer={
        <>
          <Button shape="round" variant="outline" onClick={handleClose}>
            取消
          </Button>
          <Button
            shape="round"
            theme="primary"
            onClick={handleSubmit}
            loading={saving}
            disabled={saving || !formData.title.trim() || (coverUploadRef.current?.isValidating) || (coverUploadRef.current?.hasUrlError)}
          >
            {saving ? '保存中...' : '保存'}
          </Button>
        </>
      }
    >
      <FormLayout className="edit-room-form" labelWidth={100}>
        {/* 直播间ID - 不可修改 */}
        <FormField label="直播间 ID">
          <Input
            value={room.id}
            disabled
            readonly
          />
        </FormField>

        {/* 直播间标题 */}
        <FormField label="直播间标题" requiredMark>
          <div className="form-field__input-wrapper">
            <Input
              value={formData.title}
              onChange={(value) => setFormData(prev => ({ ...prev, title: String(value) }))}
              placeholder="请输入直播间标题"
              status={getByteLength(formData.title) > 100 ? 'error' : 'default'}
              suffix={
                <span className={`input-suffix-count${getByteLength(formData.title) > 100 ? ' byte-overflow' : ''}`}>
                  {getByteLength(formData.title)}/100
                </span>
              }
            />
            {getByteLength(formData.title) > 100 && (
              <div className="form-field__error-tip">标题不能超过 100 字节</div>
            )}
          </div>
        </FormField>

        {/* 直播间封面 */}
        <FormField label="直播间封面">
          <ImageUpload
            ref={coverUploadRef}
            value={formData.coverUrl}
            onChange={(url) => {
              setFormData(prev => ({ ...prev, coverUrl: url }));
              setHasPendingCover(false);
            }}
            type="cover"
            uploadEnabled={uploadEnabled}
            cropEnabled={true}
            aspectRatio={coverAspectRatio}
            placeholder="点击或拖拽上传封面图片"
            previewHeight={140}
            maxBytes={200}
            deferUpload={uploadEnabled}
            onFileReady={(file) => setHasPendingCover(!!file)}
          />
        </FormField>

        {/* 自定义信息 - 折叠/展开区域 */}
        <div className="custom-info-section">
          <div
            className="custom-info-toggle"
            onClick={() => setCustomInfoExpanded(!customInfoExpanded)}
          >
            {customInfoExpanded ? <ChevronDownIcon size={16} /> : <ChevronRightIcon size={16} />}
            <span>自定义信息</span>
            {customInfos.length > 0 && (
              <span className="custom-info-count">{customInfos.length}</span>
            )}
          </div>
          {customInfoExpanded && (
            <div className="custom-info-container">
              {customInfos.map((info, index) => {
                const keyBytes = getByteLength(info.key);
                const valueBytes = getByteLength(info.value);
                const keyOverflow = keyBytes > CUSTOM_INFO_LIMITS.maxKeyBytes;
                const valueOverflow = valueBytes > CUSTOM_INFO_LIMITS.maxValueBytes;
                const missingKey = isCustomInfoKeyMissing(info);
                return (
                  <div key={index} className="custom-info-row">
                    <div className="custom-input-wrap">
                      <Input
                        value={info.key}
                        onChange={(value) => updateCustomInfo(index, 'key', String(value))}
                        placeholder="请输入Key"
                        status={keyOverflow || missingKey ? 'error' : 'default'}
                        tips={keyOverflow ? `Key 超出 ${CUSTOM_INFO_LIMITS.maxKeyBytes} 字节限制` : missingKey ? '填写了 Value 时必须填写 Key' : ''}
                      />
                    </div>
                    <div className="custom-input-wrap custom-value-wrap">
                      <Input
                        value={info.value}
                        onChange={(value) => updateCustomInfo(index, 'value', String(value))}
                        placeholder="请输入Value"
                        status={valueOverflow ? 'error' : 'default'}
                        tips={valueOverflow ? 'Value 超出 2KB 限制' : ''}
                      />
                    </div>
                    <Button
                      shape="square"
                      variant="text"
                      className="remove-custom-info-btn"
                      onClick={() => removeCustomInfo(index)}
                      title="删除"
                      icon={<CloseIcon size={14} />}
                    />
                  </div>
                );
              })}
              {customInfos.length < CUSTOM_INFO_LIMITS.maxCount && (
                <Button variant="text" className="add-custom-info-btn" onClick={addCustomInfo} icon={<AddIcon size={14} />} theme='primary'>
                  添加
                </Button>
              )}
            </div>
          )}
        </div>
      </FormLayout>
    </Dialog>
  );
}
